development: &non_production_settings
  :twitter:
    :consumer_key: "YMe7ifrly4DBRwet2QN2bA"
    :consumer_secret: "b958f20qYUhkNEKXbzLlsJ5NenIpAkYsytu7voXuEmc"
    :oauth_token: "554740503-YRlrHZnLVJzekbEGeeufsqPCf7KZ1uEhio3IaLAW"
    :oauth_token_secret: "ik3D1ka52qmWTbheaXkVXZFXy7sbW0hoOJ8USxeVM"
  :site:
    :title: "Fake Emmett"
    :address: "http://localhost:4567/"

test:
  <<: *non_production_settings

production:
  :site:
    :title: "Fake Emmett"
